/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arm;

import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author rahul
 */
public class addTimetable extends javax.swing.JFrame {

	/**
	 * Creates new form addTimetable
	 */
	public addTimetable(addNamelist prev) {
		namelist=prev;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbutton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        daychooser = new javax.swing.JComboBox();
        sessionnameinput = new javax.swing.JTextField();
        starthourchooser = new javax.swing.JComboBox();
        startminutechooser = new javax.swing.JComboBox();
        endhourchooser = new javax.swing.JComboBox();
        endminutechooser = new javax.swing.JComboBox();
        daylabel = new javax.swing.JLabel();
        sessionnamelabel = new javax.swing.JLabel();
        starttimelabel = new javax.swing.JLabel();
        endtimelabel = new javax.swing.JLabel();
        tolabel = new javax.swing.JLabel();
        startseparatorlabel = new javax.swing.JLabel();
        endseparatorlabel = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        notifier = new javax.swing.JLabel();
        tablescroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        createbutton = new javax.swing.JButton();
        tablemodel = new javax.swing.table.DefaultTableModel(new String[]{"Day","Timings","Subject"},0);
        day = new ArrayList<String>();
        starttime = new ArrayList<String>();
        endtime = new ArrayList<String>();
        sessionname = new ArrayList<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backbutton.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        backbutton.setText("<");

        title.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Add Timetable");

        daychooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        starthourchooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        startminutechooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        endhourchooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        endminutechooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        daylabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daylabel.setText("Day");

        sessionnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sessionnamelabel.setText("Session Name");

        starttimelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        starttimelabel.setText("Start Time");

        endtimelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endtimelabel.setText("End Time");

        tolabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        tolabel.setText("to");

        startseparatorlabel.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        startseparatorlabel.setText(":");

        endseparatorlabel.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        endseparatorlabel.setText(":");

        addbutton.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        addbutton.setText("+");
        addbutton.setPreferredSize(new java.awt.Dimension(30, 30));
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        deletebutton.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        deletebutton.setText("-");
        deletebutton.setPreferredSize(new java.awt.Dimension(30, 30));
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        notifier.setForeground(new java.awt.Color(255, 0, 0));

        table.setModel(tablemodel);
        table.getTableHeader().setReorderingAllowed(false);
        tablescroll.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
        }

        createbutton.setText("Create Class");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tablescroll)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(daychooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(daylabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sessionnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sessionnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(starthourchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startseparatorlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startminutechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(starttimelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(endhourchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endseparatorlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endminutechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(endtimelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(notifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(createbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessionnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(starttimelabel)
                    .addComponent(endtimelabel))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daychooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(starthourchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessionnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startminutechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endhourchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endminutechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tolabel)
                    .addComponent(startseparatorlabel)
                    .addComponent(endseparatorlabel)
                    .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notifier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablescroll, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        setVisible(false);
        dispose();
        namelist.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        String dayip=daychooser.getSelectedItem().toString();
        String nameip=sessionnameinput.getText();
        String startip=starthourchooser.getSelectedItem().toString()+":"+startminutechooser.getSelectedItem().toString();
        String endip=endhourchooser.getSelectedItem().toString()+":"+endminutechooser.getSelectedItem().toString();
        boolean dayused=false,timeused=false;
        
        if(sessionname.isEmpty())
        {
        	day.add(dayip);
        	sessionname.add(nameip);
        	starttime.add(startip);
        	endtime.add(endip);
        	String[] row=new String[]{dayip,startip+" - "+endip,nameip};
			tablemodel.addRow(row);
			table.setModel(tablemodel);
        }
        
        else if(startip.compareTo(endip)>0)
        	notifier.setText("End time cannot be before Start time");
        
        else
       	{
       		for(int i=0;i<sessionname.size();i++)
       		{
       			if(dayip.equals(day.get(i)))
       			{
       				dayused=true;
       				
       				if(startip.equals(starttime.get(i))||startip.equals(endtime.get(i)))
       				{
       					timeused=true;
       					break;
       				}
       				
       				if(endip.equals(starttime.get(i))||endip.equals(endtime.get(i)))
       				{
       					timeused=true;
       					break;
       				}
       				
       				if(startip.compareTo(starttime.get(i))<0)
       					if(endip.compareTo(endtime.get(i))>0)
       					{
       						timeused=true;
       						break;
       					}
       				
       				if(startip.compareTo(starttime.get(i))>0)
       					if(endip.compareTo(endtime.get(i))<0)
       					{
       						timeused=true;
       						break;
       					}
       				
       				if(startip.compareTo(starttime.get(i))>0)
       					if(startip.compareTo(endtime.get(i))<0)
       					{
       						timeused=true;
       						break;
       					}
       				
       				if(endip.compareTo(starttime.get(i))>0)
       					if(endip.compareTo(endtime.get(i))<0)
       					{
       						timeused=true;
       						break;
       					}
       			}
       		}
       		
       		if((!dayused)||(!timeused))
       		{
       			day.add(dayip);
    	   		sessionname.add(nameip);
    	   		starttime.add(startip);
    	   		endtime.add(endip);
    	   		String[] row=new String[]{dayip,startip+" - "+endip,nameip};
				tablemodel.addRow(row);
				table.setModel(tablemodel);
       		}
       		
       		else
       			notifier.setText("Session timings clash with previously entered session");
       	}
       	
       	sessionnameinput.setText("");
    }//GEN-LAST:event_addbuttonActionPerformed
    
    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        if(!sessionname.isEmpty())
        {
        	day.remove(day.size()-1);
    	   	sessionname.remove(sessionname.size()-1);
    	   	starttime.remove(starttime.size()-1);
    	   	endtime.remove(endtime.size()-1);
        	tablemodel.removeRow(sessionname.size());
        	table.setModel(tablemodel);
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

	private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed
        namelist.menu.dispose();
        namelist.dispose();
        setVisible(false);
        dispose();
        waitForCreate.main(this);
    }//GEN-LAST:event_createbuttonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(addNamelist prev) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(addTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(addTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(addTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(addTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new addTimetable(prev).setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton createbutton;
    private javax.swing.JComboBox daychooser;
    private javax.swing.JLabel daylabel;
    private javax.swing.JButton deletebutton;
    private javax.swing.JComboBox endhourchooser;
    private javax.swing.JComboBox endminutechooser;
    private javax.swing.JLabel endseparatorlabel;
    private javax.swing.JLabel endtimelabel;
    private javax.swing.JLabel notifier;
    private javax.swing.JTextField sessionnameinput;
    private javax.swing.JLabel sessionnamelabel;
    private javax.swing.JComboBox starthourchooser;
    private javax.swing.JComboBox startminutechooser;
    private javax.swing.JLabel startseparatorlabel;
    private javax.swing.JLabel starttimelabel;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tablescroll;
    private javax.swing.table.DefaultTableModel tablemodel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel tolabel;
    public addNamelist namelist;
    public List<String> day;
    public List<String> starttime;
    public List<String> endtime;
    public List<String> sessionname;
    // End of variables declaration//GEN-END:variables
}
