/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arm;

import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
/**
 *
 * @author rahul
 */
public class editNamelist extends javax.swing.JFrame {

	/**
	 * Creates new form editNamelist
	 */
	public editNamelist(String name) {
		classname=name;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbutton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        orlabel = new javax.swing.JLabel();
        applybutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        studentlabel = new javax.swing.JLabel();
        studentchooser = new javax.swing.JComboBox();
        leftidlabel = new javax.swing.JLabel();
        leftidno = new javax.swing.JTextField();
        leftnamelabel = new javax.swing.JLabel();
        leftname = new javax.swing.JTextField();
        righttitle = new javax.swing.JLabel();
        rightidlabel = new javax.swing.JLabel();
        rightidno = new javax.swing.JTextField();
        rightnamelabel = new javax.swing.JLabel();
        rightname = new javax.swing.JTextField();
        notifier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backbutton.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        backbutton.setText("<");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        title.setText("                             Edit Namelist");

        orlabel.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        orlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orlabel.setText("OR");

        applybutton.setText("Apply");
        applybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applybuttonActionPerformed(evt);
            }
        });

        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        studentlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentlabel.setText("Choose Student:");

        studentchooser.setModel(new javax.swing.DefaultComboBoxModel(util.SQLQuery(classname,"SELECT CONCAT(Name,' (',IDNo,')') AS List FROM Namelist")));
        studentchooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentchooserActionPerformed(evt);
            }
        });

        leftidlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        leftidlabel.setText("ID Number:");
        leftidno.setText((studentchooser.getSelectedItem().toString().split("\\(")[1]).split("\\)")[0]);

        leftnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        leftnamelabel.setText("Name:");
        leftname.setText(studentchooser.getSelectedItem().toString().split(" \\(")[0]);

        righttitle.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        righttitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        righttitle.setText("Add a new Student");

        rightidlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rightidlabel.setText("ID Number:");

        rightnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rightnamelabel.setText("Name:");

        notifier.setForeground(new java.awt.Color(0, 0, 255));
        notifier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(applybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rightidlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rightnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rightname, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rightidno, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(righttitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(leftidlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leftnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentchooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leftname, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(leftidno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(righttitle))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentchooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentlabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rightidno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rightidlabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rightname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rightnamelabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(leftidno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(leftidlabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(leftname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(leftnamelabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addComponent(notifier, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(applybutton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(deletebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        setVisible(false);
        dispose();
        editClass.main(null);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void studentchooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentchooserActionPerformed
		leftidno.setText((studentchooser.getSelectedItem().toString().split("\\(")[1]).split("\\)")[0]);
		leftname.setText(studentchooser.getSelectedItem().toString().split(" \\(")[0]);
    }//GEN-LAST:event_studentchooserActionPerformed

    private void applybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applybuttonActionPerformed
        String idip=leftidno.getText();
        String nameip=leftname.getText();
        String idno=(studentchooser.getSelectedItem().toString().split("\\(")[1]).split("\\)")[0];
        List<String> idexisting=new ArrayList(Arrays.asList(util.SQLQuery("ARM_config","SELECT IDNo FROM students")));
        
        if((!idexisting.contains(idip))||(idip.equals(idno)))
        {
        	util.updateIDSize(classname,idip);
			util.SQLUpdate(classname,"UPDATE Namelist SET IDNo='"+idip+"',Name='"+nameip+"' WHERE IDNo='"+idno+"'");
			util.SQLUpdate(classname,"UPDATE Percentage SET IDNo='"+idip+"' WHERE IDNo='"+idno+"'");
			util.SQLUpdate("ARM_config","UPDATE students SET IDNo='"+idip+"' WHERE IDNo='"+idno+"'");
			studentchooser.setModel(new javax.swing.DefaultComboBoxModel(util.SQLQuery(classname,"SELECT CONCAT(Name,' (',IDNo,')') AS List FROM Namelist")));
			leftidno.setText((studentchooser.getSelectedItem().toString().split("\\(")[1]).split("\\)")[0]);
			leftname.setText(studentchooser.getSelectedItem().toString().split(" \\(")[0]);
			notifier.setForeground(new java.awt.Color(0, 0, 255));
			notifier.setText("Updated Details of "+nameip+"("+idip+") Successfully");
    	}
    	
    	else
    	{
    		notifier.setForeground(new java.awt.Color(255, 0, 0));
    		notifier.setText("ID Number is used");
    	}
    }//GEN-LAST:event_applybuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        String idno=(studentchooser.getSelectedItem().toString().split("\\(")[1]).split("\\)")[0];
        
        util.SQLUpdate(classname,"DELETE FROM Namelist WHERE IDNo='"+idno+"'");
		util.SQLUpdate(classname,"DELETE FROM Percentage WHERE IDNo='"+idno+"'");
		util.SQLUpdate("ARM_config","DELETE FROM students WHERE IDNo='"+idno+"'");
		studentchooser.setModel(new javax.swing.DefaultComboBoxModel(util.SQLQuery(classname,"SELECT CONCAT(Name,' (',IDNo,')') AS List FROM Namelist")));
		leftidno.setText((studentchooser.getSelectedItem().toString().split("\\(")[1]).split("\\)")[0]);
		leftname.setText(studentchooser.getSelectedItem().toString().split(" \\(")[0]);
		notifier.setForeground(new java.awt.Color(0, 0, 255));
		notifier.setText("Deleted '"+idno+"' Successfully");
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        String idip=rightidno.getText();
        String nameip=rightname.getText();
        List<String> idexisting=new ArrayList(Arrays.asList(util.SQLQuery("ARM_config","SELECT IDNo FROM students")));
        String[] session=util.SQLQuery(classname,"SELECT DISTINCT SessionName FROM Percentage");
        
        if(!idexisting.contains(idip))
        {							
			util.updateIDSize(classname,idip);
			util.SQLUpdate(classname,"INSERT INTO Namelist(IDNo,Name) VALUES('"+idip+"','"+nameip+"')");
			for(int i=0;i<session.length;i++)
				util.SQLUpdate(classname,"INSERT INTO Percentage(IDNo,SessionName) VALUES('"+idip+"','"+session[i]+"')");
			util.SQLUpdate("ARM_config","INSERT INTO students VALUES('"+idip+"','"+classname+"')");
			studentchooser.setModel(new javax.swing.DefaultComboBoxModel(util.SQLQuery(classname,"SELECT CONCAT(Name,' (',IDNo,')') AS List FROM Namelist")));
			leftidno.setText((studentchooser.getSelectedItem().toString().split("\\(")[1]).split("\\)")[0]);
			leftname.setText(studentchooser.getSelectedItem().toString().split(" \\(")[0]);
			notifier.setForeground(new java.awt.Color(0, 0, 255));
			notifier.setText("Added Student "+nameip+"("+idip+") Successfully");
    	}
    	
    	else
    	{
    		notifier.setForeground(new java.awt.Color(255, 0, 0));
    		notifier.setText("ID Number is used");
    	}
    }//GEN-LAST:event_addbuttonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String name) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			util.setLookAndFeel();
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(editNamelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(editNamelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(editNamelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(editNamelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new editNamelist(name).setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton applybutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel leftidlabel;
    private javax.swing.JTextField leftidno;
    private javax.swing.JTextField leftname;
    private javax.swing.JLabel leftnamelabel;
    private javax.swing.JLabel notifier;
    private javax.swing.JLabel orlabel;
    private javax.swing.JLabel rightidlabel;
    private javax.swing.JTextField rightidno;
    private javax.swing.JTextField rightname;
    private javax.swing.JLabel rightnamelabel;
    private javax.swing.JLabel righttitle;
    private javax.swing.JComboBox studentchooser;
    private javax.swing.JLabel studentlabel;
    private javax.swing.JLabel title;
    private String classname;
    // End of variables declaration//GEN-END:variables
}
