/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arm;

/**
 *
 * @author rahul
 */
public class mainUI extends javax.swing.JFrame {

    /**
     * Creates new form mainUI
     */
    public mainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffbutton = new javax.swing.JButton();
        adminbutton = new javax.swing.JButton();
        idinput = new javax.swing.JTextField();
        applabel = new javax.swing.JLabel();
        notifier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(true);

        staffbutton.setText("Staff Login");
        staffbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffbuttonActionPerformed(evt);
            }
        });

        adminbutton.setText("Admin Login");
        adminbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbuttonActionPerformed(evt);
            }
        });

        idinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idinputActionPerformed(evt);
            }
        });

        applabel.setFont(new java.awt.Font("Cantarell", 0, 44)); // NOI18N
        applabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        applabel.setLabelFor(this);
        applabel.setText("ARM - The Attendance Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(applabel, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addComponent(idinput)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(staffbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(applabel, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(idinput, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notifier, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idinputActionPerformed
        String idno=idinput.getText();
        String rep=student.update(idno);
        
        if(rep.contains("Attendance given for"))
        	notifier.setForeground(new java.awt.Color(0, 0, 255));
        
        else if(rep.contains("You've already entered attendance for"))
        	notifier.setForeground(new java.awt.Color(255, 145, 0));
        
        else
        	notifier.setForeground(new java.awt.Color(255, 0, 0));
        
        idinput.setText("");
        notifier.setText(rep);
    }//GEN-LAST:event_idinputActionPerformed

    private void staffbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffbuttonActionPerformed
        loginUI.main("Staff",this);
    }//GEN-LAST:event_staffbuttonActionPerformed
    
    private void adminbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbuttonActionPerformed
        loginUI.main("Admin",this);
    }//GEN-LAST:event_adminbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
			Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e) {
        	e.printStackTrace();
        }
		setup.firstRun();
		int temp=setup.createReports();
		boolean first_run=false;

        if(temp==1)
        	first_run=true;

        if(!first_run)
        {
        	/* Set the Nimbus look and feel */
        	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        	 */
        	try {
        	    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
       		} catch (ClassNotFoundException ex) {
        	    java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        	} catch (InstantiationException ex) {
       	    	java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        	} catch (IllegalAccessException ex) {
            	java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            	java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        	}
        	//</editor-fold>

        	/* Create and display the form */
        	java.awt.EventQueue.invokeLater(new Runnable() {
            	public void run() {
            	    new mainUI().setVisible(true);
            	}
        	});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbutton;
    private javax.swing.JLabel applabel;
    private javax.swing.JTextField idinput;
    private javax.swing.JLabel notifier;
    private javax.swing.JButton staffbutton;
    // End of variables declaration//GEN-END:variables
}
