/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arm;

import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author rahul
 */
public class reportViewerUI extends javax.swing.JFrame {

	/**
	 * Creates new form reportViewerUI
	 */
	public reportViewerUI(String name,String datein,javax.swing.JFrame prev) {
		classname=name;
		date=datein;
		previous=prev;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablescroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        datelabel = new javax.swing.JLabel();
        editbutton = new javax.swing.JButton();
        printbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

		populateRows();

        title.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("View Report");

        backbutton.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        backbutton.setText("<");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

		datelabel.setText(new String(date).replace("_","-"));
        datelabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        datelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        editbutton.setText("Edit");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });

        printbutton.setText("Print");
        printbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablescroll, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editbutton)
                        .addGap(18, 18, 18)
                        .addComponent(printbutton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editbutton)
                    .addComponent(printbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablescroll, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
       	setVisible(false);
       	dispose();
       	previous.setVisible(true);
   	}//GEN-LAST:event_backbuttonActionPerformed

   	private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
       	setVisible(false);
       	dispose();
       	reportEditorUI.main(classname,date,previous);
   	}//GEN-LAST:event_editbuttonActionPerformed

   	private void printbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbuttonActionPerformed
   		try {
   			table.print();
   		}catch(java.awt.print.PrinterException e) {
   			e.printStackTrace();
   		}
   	}//GEN-LAST:event_printbuttonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String name,String datein,javax.swing.JFrame prev) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(reportViewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(reportViewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(reportViewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(reportViewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new reportViewerUI(name,datein,prev).setVisible(true);
			}
		});
	}
	
	private String[] columnNames()
	{
		List<String> list=new ArrayList<String>();
		String idno=util.SQLQuery(classname,"SELECT DISTINCT IDNo FROM "+date)[0];
		String[] session=util.SQLQuery(classname,"SELECT SessionName FROM Timetable JOIN "+date+" ON Timetable.Session="+date+".Session WHERE Day='"+util.getDay(date)+"' AND IDNo='"+idno+"'");
		list.add("Name");
		list.add("ID Number");
		for(int i=0;i<session.length;i++)
			list.add(session[i]);
		
		return list.toArray(new String[list.size()]);
	}
	
	private void populateRows()
	{
		javax.swing.table.DefaultTableModel tablemodel=new javax.swing.table.DefaultTableModel(columnNames(),0);
		String[] idno=util.SQLQuery(classname,"SELECT DISTINCT IDNo FROM "+date);
		String[] name=util.SQLQuery(classname,"SELECT DISTINCT Name FROM Namelist JOIN "+date+" ON Namelist.IDNo="+date+".IDNo");
		String[] session=util.SQLQuery(classname,"SELECT DISTINCT Session FROM "+date);
		String[] status=util.SQLQuery(classname,"SELECT Status FROM "+date);
		int k=0;
							
		for(int i=0;i<idno.length;i++)
		{
			List<String> list=new ArrayList<String>();
			
			list.add(name[i]);
			list.add(idno[i]);
			for(int j=0;j<session.length;j++)
			{
				if(status[k]==null)
					status[k]="Absent";
				list.add(status[k++]);
			}
			Object[] obj=list.toArray();
			tablemodel.addRow(obj);
		}
		
		table.setModel(tablemodel);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablescroll.setViewportView(table);
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel datelabel;
    private javax.swing.JButton editbutton;
    private javax.swing.JButton printbutton;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tablescroll;
    private javax.swing.JLabel title;
    private javax.swing.JFrame previous;
    private String classname;
    private String date;
    // End of variables declaration//GEN-END:variables
}
