/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arm;

import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author rahul
 */
public class reportEditorUI extends javax.swing.JFrame {

	/**
	 * Creates new form reportEditorUI
	 */
	public reportEditorUI(String name,String datein,javax.swing.JFrame prev) {
		classname=name;
		date=datein;
		previous=prev;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbutton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        idchooser = new javax.swing.JComboBox();
        statuslabel = new javax.swing.JLabel();
        statuschooser = new javax.swing.JComboBox();
        applybutton = new javax.swing.JButton();
        sessionchooser = new javax.swing.JComboBox();
        sessionlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backbutton.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        backbutton.setText("<");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
		
        title.setText("Edit Report ("+new String(date).replace("_","-")+")");
        title.setFont(new java.awt.Font("Cantarell", 1, 28)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        idlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idlabel.setText("Student:");
        idlabel.setFont(new java.awt.Font("Cantarell", 0, 16));

        idchooser.setModel(new javax.swing.DefaultComboBoxModel(listStudents()));
        idchooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idchooserActionPerformed(evt);
            }
        });
        
        sessionlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sessionlabel.setText("Session:");
        sessionlabel.setFont(new java.awt.Font("Cantarell", 0, 16));
        
        sessionchooser.setModel(new javax.swing.DefaultComboBoxModel(listSessions()));
        sessionchooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionchooserActionPerformed(evt);
            }
        });

        statuslabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statuslabel.setText("Status:");
        statuslabel.setFont(new java.awt.Font("Cantarell", 0, 16));

        statuschooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Present","Absent","On Leave","On Duty"}));
        

        applybutton.setText("Apply");
        applybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applybuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(applybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statuschooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(sessionlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sessionchooser, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idchooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idchooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sessionchooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statuschooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(statuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(applybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idchooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idchooserActionPerformed
		statuschooser.setSelectedIndex(currentStatus());
	}//GEN-LAST:event_idchooserActionPerformed

	private void sessionchooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionchooserActionPerformed
		statuschooser.setSelectedIndex(currentStatus());
	}//GEN-LAST:event_sessionchooserActionPerformed

    private void applybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applybuttonActionPerformed
        int session=sessionchooser.getSelectedIndex()+1;
        String status=statuschooser.getSelectedItem().toString();
        String idno=(idchooser.getSelectedItem().toString().split("\\(")[1]).split("\\)")[0];
        String currentstatus=util.SQLQuery(classname,"SELECT Status FROM "+date+" WHERE Session="+session+" AND IDNo='"+idno+"'")[0];
        String[] sessionname=util.SQLQuery(classname,"SELECT DISTINCT SessionName FROM Timetable WHERE Day='"+util.getDay(date)+"'");
        
        if(status.equals("Present"))
        {
        	if((currentstatus==null)||(!currentstatus.contains(":")))
        	{
        		util.SQLUpdate(classname,"UPDATE "+date+" SET Status='Present' WHERE Session="+session+" AND IDNo='"+idno+"'");
        		
        		if((currentstatus==null)||((!currentstatus.equals("Present"))&&(!currentstatus.equals("OD"))))
        			util.SQLUpdate(classname,"UPDATE Percentage SET Attended=Attended+1 WHERE IDNo='"+idno+"' AND SessionName='"+sessionname[session-1]+"'");
        	}
        }
        
        else if(status.equals("Absent"))
        {
        	util.SQLUpdate(classname,"UPDATE "+date+" SET Status=null WHERE Session="+session+" AND IDNo='"+idno+"'");
        	
        	if((currentstatus!=null)&&(!currentstatus.equals("Leave")))
        		util.SQLUpdate(classname,"UPDATE Percentage SET Attended=Attended-1 WHERE IDNo='"+idno+"' AND SessionName='"+sessionname[session-1]+"'");
        }
        
        else if(status.equals("On Leave"))
        {
        	util.SQLUpdate(classname,"UPDATE "+date+" SET Status='Leave' WHERE Session="+session+" AND IDNo='"+idno+"'");
        	
        	if((currentstatus!=null)&&(!currentstatus.equals("Leave")))
        		util.SQLUpdate(classname,"UPDATE Percentage SET Attended=Attended-1 WHERE IDNo='"+idno+"' AND SessionName='"+sessionname[session-1]+"'");
        		
        }
        
        else
        {
        	util.SQLUpdate(classname,"UPDATE "+date+" SET Status='On Duty' WHERE Session="+session+" AND IDNo='"+idno+"'");
        	if((currentstatus==null)||((!currentstatus.contains(":"))&&(!currentstatus.equals("Present"))&&(!currentstatus.equals("OD"))))
        		util.SQLUpdate(classname,"UPDATE Percentage SET Attended=Attended+1 WHERE IDNo='"+idno+"' AND SessionName='"+sessionname[session-1]+"'");
        }
    }//GEN-LAST:event_applybuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        setVisible(false);
        dispose();
        previous.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String name,String datein,javax.swing.JFrame prev) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(reportEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(reportEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(reportEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(reportEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new reportEditorUI(name,datein,prev).setVisible(true);
			}
		});
	}
	
	private String[] listStudents()
	{
		List<String> list=new ArrayList<String>();
		String[] idno=util.SQLQuery(classname,"SELECT DISTINCT IDNo FROM "+date),name=util.SQLQuery(classname,"SELECT DISTINCT Name FROM Namelist JOIN "+date+" ON Namelist.IDNo="+date+".IDNo");
		
		for(int i=0;i<idno.length;i++)
			list.add(name[i]+" ("+idno[i]+")");
		
		return list.toArray(new String[list.size()]);
	}
	
	private String[] listSessions()
	{
		String idno=util.SQLQuery(classname,"SELECT DISTINCT IDNo FROM "+date)[0];
		String[] session=util.SQLQuery(classname,"SELECT SessionName FROM Timetable JOIN "+date+" ON Timetable.Session="+date+".Session WHERE Day='"+util.getDay(date)+"' AND IDNo='"+idno+"'");
		
		return session;
	}
	
	private int currentStatus()
	{
		int idposn=idchooser.getSelectedIndex(),sessionposn=sessionchooser.getSelectedIndex()+1;
		String[] idno=util.SQLQuery(classname,"SELECT DISTINCT IDNo FROM "+date);
		String[] status=util.SQLQuery(classname,"SELECT Status FROM "+date+" WHERE IDNo='"+idno[idposn]+"' AND Session="+sessionposn);
		
		if(status==null)
			return 1;
			
		else if(status.equals("Leave"))
			return 2;
		
		else if(status.equals("OD"))
			return 3;
			
		else
			return 0;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applybutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JComboBox idchooser;
    private javax.swing.JLabel idlabel;
    private javax.swing.JComboBox sessionchooser;
    private javax.swing.JLabel sessionlabel;
    private javax.swing.JComboBox statuschooser;
    private javax.swing.JLabel statuslabel;
    private javax.swing.JLabel title;
    private javax.swing.JFrame previous;
    private String classname;
    private String date;
    // End of variables declaration//GEN-END:variables
}
